### PR TITLE
Identity Resolution

### PR DESCRIPTION
**Pull request by marusic1514**
Changed the input on identity resolution for userId to match up the new format

Resolves ENG-2645

- - -
This change is [Reviewable](https://reviewable.io/reviews/goplayerzero/sdk-java/1)

### CODE REVIEW

**Review by sepatel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/sdk-java/1)* status: all files reviewed, 1 unresolved discussion (waiting on @marusic1514)

*[a discussion](https://reviewable.io/reviews/goplayerzero/sdk-java/1#-N_2x6Y80oFpexgdtekJ:-N_2x6Y80oFpexgdtekK:b-khhhic) (no related file):*
Need the story that is linked to this please.

___

**Review by sepatel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/sdk-java/1)* status: all files reviewed, 1 unresolved discussion (waiting on @marusic1514)

**Review by marusic1514 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/sdk-java/1)* status: all files reviewed, 1 unresolved discussion (waiting on @marusic1514)

**Comment by marusic1514** [comment]
<details><summary><i>Previously, sepatel (Ryba) wrote…</i></summary><blockquote>

Need the story that is linked to this please.
</blockquote></details>

ENG-2645

**Review by sepatel — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/sdk-java/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marusic1514)

**Pull request merged**
